# Generated by Django 5.2.1 on 2025-05-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='False-default,True-Trending'),
        ),
    ]
