# Generated by Django 5.2.1 on 2025-05-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='product_qty',
        ),
    ]
